# Generated by Django 4.1 on 2022-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
