# Generated by Django 4.1 on 2022-10-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pet_app", "0003_alter_funcionario_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(blank=True, max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("profissao", models.CharField(max_length=25)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnderecoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=30)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo",
            field=models.IntegerField(
                choices=[
                    (1, "Médico Veterinario"),
                    (2, "Financeiro"),
                    (3, "Atendimento"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nascimento",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("peso", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ca", "Cachorro"),
                            ("Ga", "Gato"),
                            ("Pa", "Pássaro"),
                            ("Ha", "Hamister"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pr", "Preto"),
                            ("Br", "Branco"),
                            ("Ci", "Cinza"),
                            ("Ma", "Malhado"),
                            ("Cr", "Creme"),
                            ("Mr", "Marrom"),
                            ("Am", "Amarelo"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("raca", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("Fe", "Femea"), ("Ma", "Macho")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pet_app.cliente",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsultaPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "doutor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ma", "Maria Lima"),
                            ("Fc", "Fernanda Cardoso Lira"),
                            ("Af", "Amanda Finamor"),
                            ("Vm", "Victoria Misson"),
                            ("As", "Amanda dos Santos Silva"),
                            ("Cv", "Cássia Vasconcellos"),
                            ("Rp", "Regina Elis Pascoal"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("motivo_consulta", models.CharField(max_length=200)),
                ("medicamento_atual", models.TextField()),
                ("medicamentos_prescritos", models.TextField()),
                ("exames", models.TextField()),
                (
                    "especialidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cg", "Clinico Geral"),
                            ("Cd", "Cardiologia"),
                            ("De", "Dermatologia"),
                            ("Fi", "Fisioterapia"),
                            ("He", "Hematologia"),
                            ("Ne", "Neurologia"),
                            ("Or", "Ortopedia"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("observacoes", models.TextField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet_app.pet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pet_app.enderecocliente",
            ),
        ),
    ]
